name: FlippingPages
favicon: null
layout_spectrum: 0.3218469007406384
typography_spectrum: 0.9154971074312925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49631882435642183
  lightness: 0.6738013848662376
  saturation: 0.7074038237333298
  rhythmicContrast: 0.5615985691547394
purpose: []
